import Head from 'next/head'
import Main from 'components/Main'
import Cate from 'components/Cate'
import Products from 'components/Products';
import Footer from 'components/Footer';
import { useTheme } from 'next-themes';
import Icons from 'components/Icons';


export default function Home() {


  return (
    <div>
    
      <Head>
        <title>Dream_Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <Cate/>
      <Products/>
      <Footer/>
    </div>
  )
}
